version: "3.8"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env 

  node_app:
    container_name: node_app
    restart: unless-stopped
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - .env
